### ISSUE TITLE
Allow customization of session closure

### ISSUE THREAD

**Issue by CaselIT** [vytas7/falcon-sqla#1]
The default logic, commit on success, rollback on failure is a sensible one
https://github.com/vytas7/falcon-sqla/blob/e4d7865892c1111c49ecb7e06a7b2a425990ec73/falcon_sqla/middleware.py#L53-L56

maybe it could be useful to add the ability of a resource to customize this logic.
I'm not sure how to best implement it. Probably a function in the resource class that returns what to do (commit, rollback, nothing) is the best solution.

**Comment by CaselIT** [comment]
If we go with a function or method on the resource instance, I think it should return how the session should be disposed. The possible options are:
- commit
- rollback
- default (meaning do the default logic)
- do-nothing (meaning that no commit or rollback will occur, the session with only be closed)

What should the callable return? a string or an enum we define with these options?

**Comment by vytas7** [comment]
I went for an enum with four options along the lines of your bullet list.
