### ISSUE TITLE
ClosingStreamWrapper should implement a read method

### ISSUE THREAD

**Issue by CaselIT** [vytas7/falcon-sqla#9]
`falcon-sqla` wraps streams using `ClosingStreamWrapper`.

This class does not have a read attribute, and it causes falcon to not use the `wsgi_file_wrapper `
https://github.com/falconry/falcon/blob/2556abce9afd9e0ea55d6aada09c64c311ca688e/falcon/api.py#L832

This can lead to large performance regressions when the stream is a file, since it can get iterated over one byte at the time.
See https://github.com/Pylons/waitress/issues/291

**Comment by vytas7** [comment]
Touché... will fix.

**Comment by vytas7** [comment]
Hopefully fixed now, feel free to test the unstable version: `pip install falcon-sqla==0.2.0a1`

**Comment by vytas7** [comment]
`falcon-sqla==0.2.0` (including this fix) has recently been released.

**Comment by CaselIT** [comment]
Nice, thanks for the heads up. Will update and remove the workaround.
